name: Windows Build

on:
  push:
    branches: [ "dev", "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4

      - name: Устанавливаем Qt 6
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Устанавливаем ZLIB (vcpkg)
        run: |
          vcpkg install zlib:x64-windows
          vcpkg integrate install

      - name: Настраиваем CMake
        # ВАЖНО: Добавили -S FinWizard_dll, так как корень проекта там
        run: cmake -B build -S FinWizard_dll -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Собираем проект
        run: cmake --build build --config Release

      - name: Подготавливаем файлы (windeployqt)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path FinWizard_Release

          # Копируем EXE. Используем поиск, так как путь может отличаться (build/src/gui/Release/...)
          Get-ChildItem -Path build -Filter FinWizardGui.exe -Recurse | Copy-Item -Destination FinWizard_Release\

          # Копируем zlib.dll из папки vcpkg
          Copy-Item "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin\zlib1.dll" -Destination FinWizard_Release\

          # Запускаем сборку зависимостей Qt
          windeployqt FinWizard_Release\FinWizardGui.exe

      - name: Загружаем готовый результат
        uses: actions/upload-artifact@v4
        with:
          name: FinWizard-Windows-App
          path: FinWizard_Release\
