name: Windows Build

on:
  push:
    branches: [ "dev", "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4

      - name: Устанавливаем Qt 6
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qt5compat'

      - name: Устанавливаем ZLIB (vcpkg)
        run: |
          vcpkg install zlib:x64-windows
          vcpkg integrate install

      - name: Настраиваем CMake
        run: cmake -B build -S FinWizard_dll -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Собираем проект
        run: cmake --build build --config Release

      - name: Подготавливаем файлы (windeployqt)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path FinWizard_Release

          $exeFile = Get-ChildItem -Path build -Filter FinWizardGui.exe -Recurse | Select-Object -First 1
          if ($exeFile) {
              Copy-Item $exeFile.FullName -Destination FinWizard_Release\
              Write-Host "Found EXE at: $($exeFile.FullName)"
          } else {
              Write-Error "FinWizardGui.exe не найден в папке build!"
              exit 1
          }

          Copy-Item "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin\zlib1.dll" -Destination FinWizard_Release\
          windeployqt FinWizard_Release\FinWizardGui.exe

      - name: Собираем установщик (Inno Setup)
        shell: pwsh
        run: |
          # Создаем папку для готового Setup.exe
          New-Item -ItemType Directory -Force -Path Output

          $iscc = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          $sourceDir = "$pwd\FinWizard_Release"
          $outDir = "$pwd\Output"

          # Автоматически ищем файл setup.iss в репозитории
          $issFile = Get-ChildItem -Path . -Filter setup.iss -Recurse | Select-Object -First 1

          if ($issFile) {
              Write-Host "Found ISS at: $($issFile.FullName)"
              # Запускаем Inno Setup, передавая ему пути через макросы
              & $iscc /DMySourceDir="$sourceDir" /DMyOutDir="$outDir" $issFile.FullName
          } else {
              Write-Error "Файл setup.iss не найден!"
              exit 1
          }

      - name: Загружаем готовый результат
        uses: actions/upload-artifact@v4
        with:
          name: FinWizard-Windows-Installer
          # Загружаем только папку Output, где лежит наш Setup.exe
          path: Output\
