name: Windows Build

on:
  push:
    branches: [ "dev", "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4

      - name: Устанавливаем Qt 6
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      # ---- ДОБАВЛЕНО: Установка ZLIB через vcpkg ----
      - name: Устанавливаем ZLIB (vcpkg)
        run: |
          vcpkg install zlib:x64-windows
          vcpkg integrate install
      # -----------------------------------------------

      # ВАЖНО: Добавили путь к vcpkg в команду CMake, чтобы он нашел ZLIB
      - name: Настраиваем CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Собираем проект
        run: cmake --build build --config Release

      - name: Подготавливаем файлы (windeployqt)
        run: |
          mkdir FinWizard_Release
          copy build\src\gui\Release\FinWizardGui.exe FinWizard_Release\
          # Копируем саму zlib.dll, чтобы она была рядом с exe!
          copy "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin\zlib1.dll" FinWizard_Release\
          windeployqt FinWizard_Release\FinWizardGui.exe

      - name: Загружаем готовый результат
        uses: actions/upload-artifact@v4
        with:
          name: FinWizard-Windows-App
          path: FinWizard_Release\
